version: '3'

services:
  postgres:
    image: postgres:14.5
    container_name: postgres_14
    hostname: ${DB_HOST_DOCKER}
    ports:
      - 6543:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  dash_app:
    ports:
      - ${APP_PORT}:${APP_PORT}
    build: .
    container_name: ${APP_NAME}
    volumes:
      - .:/app
    links:
      - postgres
    depends_on:
      postgres:
        condition: 
          service_healthy